// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezzhzuzctsqavksrmjuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6emh6dXpjdHNxYXZrc3JtanV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjQ2NzcsImV4cCI6MjA3MDM0MDY3N30.8E9kM5iwxYEUyMXojxpCjlPkcZ36cW1Gp4LZ1lkEos0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});